
#HOME PAGE
ALL_LAPTOPS_A="CGtC98"
NAME_SPAN="VU-ZEz"
HIGHLIGHTS_LI="_7eSDEz"
DESCRIPTION_DIV="_4gvKMe"
FEATURE_TITLE_DIV="_9GQWrZ"
SPECIFICATIONS_PARENT_DIV="_1OjC5I"
REVIEW_COUNT_DIV="_23J90q RcXBOT"
RATINGS_DIV="HO1dRb"
A_REVIEW_DIV="col EPCmJX"
QUESTIONS_ANSWERS_TITLE_DIV="S1lW7R wK1mEC col"
ALL_QUESTIONS_A="QqFHMw WPJGw9"
A_QUESTION_DIV="BZMA+t"

#RATINGS PAGE
RATINGS_OVERALL_DIV="ipqd2A"
RATING_URLS_PARENT_DIV="+uoMff"
RATING_SCORE_TEXT="_2DdnFS"

#REVIEWS PAGE
REVIEW_PAGE_NUMBERS_DIV="_1G0WLw mpIySA"
REVIEW_PAGE_A_REVIEW_DIV="col EPCmJX Ma1fCG"
HIDDEN_CONTENT_SPAN="b4x-fr"

#QUESTIONS PAGE
LOAD_MORE_A="Ve-O24"
